Repository theohbrothers/PSModulePublisher, pull requests merged in 2023-09, with the labels that each got.

#31 Enhancement: Install RequiredModules before generating module manifest in `Invoke-Build.ps1`
  src/PSModulePublisher/Public/Invoke-Build.ps1
Labels: enhancement

#34 Enhancement: Show warning in `Invoke-Publish.ps1` if `dotnet` cli is not found
  src/PSModulePublisher/Public/Invoke-Publish.ps1
Labels: enhancement

#36 Enhancement: Disable `dotnet` telemetry in `Publish-Module.ps1`
  src/PSModulePublisher/Private/Publish-Module.ps1
Labels: enhancement

#33 Enhancement (ci): Add test and release jobs
  .github/release-drafter.yml
  .github/workflows/ci-master-pr.yml
  README.md
  test/test.ps1
Labels: enhancement

#37 Docs (readme): Fix `ci-master-pr` workflow badge reference
  README.md
Labels: docs

#38 Enhancement (vars): Add support for predefining project base directory
  src/PSModulePublisher/Private/Get-ProjectVariables.ps1
Labels: enhancement

#39 Fix (vars): Fix support for predefining project base directory
  src/PSModulePublisher/Private/Get-ProjectVariables.ps1
Labels: fix

#35 Enhancement (ci): Add integration tests
  .github/workflows/ci-master-pr.yml
  .vscode/tasks.json
  src/PSModulePublisher/Invoke-PSModulePublisher.Tests.ps1
  test/Mock-Module/build/definitions/modulemanifest.ps1
  test/Mock-Module/src/Mock-Module/Mock-Module.psd1
  test/Mock-Module/src/Mock-Module/Mock-Module.psm1
Labels: enhancement

#40 Enhancement (ci): Bump test jobs to latest powershell patch images
  .github/workflows/ci-master-pr.yml
Labels: enhancement

#41 Docs (readme): Add documentation on predefining project base directory
  README.md
Labels: docs

#42 Docs (readme): Tweak documentation on predefining project base directory
  README.md
Labels: docs
